### ISSUE TITLE
System.App not available

### ISSUE THREAD

**Issue by cwollenhaupt** [VFPX/GDIPlusX#3]
While the documentation mentions a System.APP file among others, this file isn't anywhere in the repository nor is it provided as a release. My guess is that it disappeared during the migration from CodePlex many years ago.

**Comment by ddTech** [comment]
Christoph, 
yes, it looks just like that. 
I just had a look in my local download folder from ancient times and found a GDIPlusX_Source_v1.20.zip which containes the system.app as well as a system_lean.app and a readme_source.htm as well as a subfolder [source] with mainly the files found here under Source.

However, the FoxCharts Project does have the system.app 

https://github.com/VFPX/FoxCharts/tree/master/FoxCharts1.47b/Source

Let me know, if You need the file from me

Kind regards 

Frank

**Comment by DougHennig** [comment]
I cleaned up the repository a little and included System.app.
