### ISSUE TITLE
GDIPlusX update in thor

### ISSUE THREAD

**Issue by mksharmamk** [VFPX/GDIPlusX#5]
GDIPlusX update not showing pending update in thor - Check for Updates

![image](https://github.com/user-attachments/assets/8043d62b-e88e-43c5-ba4d-718f25d2bd6e)

Warm regards,
mk.

**Comment by DougHennig** [comment]
Not all projects show the correct information in the Check for Updates dialog. It is up to the manager of that project to keep the information current. That being said, I may update this sometime in the future.

**Comment by DougHennig** [comment]
This has been updated.
